// Generated by CoffeeScript 1.6.3
var hooks;

hooks = require('hooks');

hooks.before('GET /machines -> 200', function(test, done) {
  test.request.query['key'] = 'value'
  test.request.headers['header'] = '123232323';
  console.log('before-hook-GET-machines');
  return done();
});
